version: '3'

services:
  voting:
    build:
      context: ./voting
      dockerfile: ./voting.dockerfile
    restart: always
    ports:
      - "8090:80"
    deploy:
      mode: replicated
      replicas: 1
